-- GruvboxNeon — generated by Noctalia's template engine. Do not edit by hand;
-- re-render with `noctalia msg templates-apply`.

vim.o.background = "{{mode}}"
vim.g.colors_name = "gruvbox-neon"

local c = {
    bg            = "{{colors.surface.default.hex}}",
    bg_dim        = "{{colors.surface_dim.default.hex}}",
    bg_variant    = "{{colors.surface_variant.default.hex}}",
    fg            = "{{colors.on_surface.default.hex}}",
    fg_muted      = "{{colors.on_surface_variant.default.hex}}",
    fg_dim        = "{{colors.terminal_bright_black.default.hex}}",
    green         = "{{colors.primary.default.hex}}",
    on_green      = "{{colors.on_primary.default.hex}}",
    blue          = "{{colors.secondary.default.hex}}",
    on_blue       = "{{colors.on_secondary.default.hex}}",
    yellow        = "{{colors.tertiary.default.hex}}",
    on_yellow     = "{{colors.on_tertiary.default.hex}}",
    red           = "{{colors.error.default.hex}}",
    on_red        = "{{colors.on_error.default.hex}}",
    pink          = "{{colors.outline.default.hex}}",
    border        = "{{colors.outline_variant.default.hex}}",
    purple        = "{{colors.terminal_normal_magenta.default.hex}}",
    aqua          = "{{colors.terminal_normal_cyan.default.hex}}",
    white         = "{{colors.terminal_bright_white.default.hex}}",
}

local hi = function(group, spec)
    vim.api.nvim_set_hl(0, group, spec)
end

local links = function(link, target)
    vim.api.nvim_set_hl(0, link, { link = target })
end

-- Editor UI ------------------------------------------------------------------
hi("Normal",       { fg = c.fg, bg = c.bg })
hi("NormalFloat",  { fg = c.fg, bg = c.bg_dim })
hi("FloatBorder",  { fg = c.pink, bg = c.bg_dim })
hi("FloatTitle",   { fg = c.pink, bg = c.bg_dim, bold = true })
hi("Cursor",       { fg = c.bg, bg = c.fg })
hi("CursorLine",   { bg = c.bg_dim })
hi("CursorColumn", { bg = c.bg_dim })
hi("ColorColumn",  { bg = c.bg_variant })
hi("Conceal",      { fg = c.fg_muted })
hi("LineNr",       { fg = c.fg_dim })
hi("CursorLineNr", { fg = c.yellow, bold = true })
hi("SignColumn",   { bg = c.bg })
hi("VertSplit",    { fg = c.border })
hi("WinSeparator", { fg = c.border })
hi("StatusLine",   { fg = c.fg, bg = c.bg_variant })
hi("StatusLineNC", { fg = c.fg_muted, bg = c.bg_dim })
hi("WinBar",       { fg = c.fg_muted, bg = c.bg })
hi("WinBarNC",     { fg = c.fg_dim, bg = c.bg })
hi("Visual",       { fg = c.on_blue, bg = c.blue })
hi("Search",       { fg = c.on_yellow, bg = c.yellow })
hi("IncSearch",    { fg = c.on_yellow, bg = c.yellow, bold = true, underline = true })
hi("FFFGrepMatch", { fg = c.on_red, bg = c.pink, bold = true, nocombine = true })
hi("FFFPreviewCursorLine", { underline = true, sp = c.pink })
hi("MatchParen",   { fg = c.yellow, bg = c.bg_variant, bold = true })
hi("Pmenu",        { fg = c.fg, bg = c.bg_dim })
hi("PmenuSel",     { fg = c.on_green, bg = c.green, bold = true })
hi("PmenuSbar",    { bg = c.bg_dim })
hi("PmenuThumb",   { bg = c.pink })
hi("WildMenu",     { fg = c.on_green, bg = c.green })
hi("NonText",      { fg = c.fg_dim })
hi("Whitespace",   { fg = c.fg_dim })
hi("EndOfBuffer",  { fg = c.bg_dim })
hi("Directory",    { fg = c.blue, bold = true })
hi("Title",        { fg = c.green, bold = true })
hi("MoreMsg",      { fg = c.green, bold = true })
hi("ModeMsg",      { fg = c.fg_muted, bold = true })
hi("Question",     { fg = c.green, bold = true })
hi("ErrorMsg",     { fg = c.red, bold = true })
hi("WarningMsg",   { fg = c.yellow, bold = true })
hi("Folded",       { fg = c.fg_muted, bg = c.bg_dim })
hi("FoldColumn",   { fg = c.fg_dim, bg = c.bg })
hi("SpecialKey",   { fg = c.pink })
hi("Underlined",   { fg = c.blue, underline = true })
hi("Ignore",       { fg = c.fg_dim })
hi("Debug",        { fg = c.pink })

hi("SpellBad",   { fg = c.red, undercurl = true })
hi("SpellCap",   { fg = c.blue, undercurl = true })
hi("SpellLocal", { fg = c.aqua, undercurl = true })
hi("SpellRare",  { fg = c.pink, undercurl = true })

-- Diagnostics ----------------------------------------------------------------
hi("DiagnosticError",        { fg = c.red })
hi("DiagnosticWarn",         { fg = c.yellow })
hi("DiagnosticInfo",         { fg = c.blue })
hi("DiagnosticOk",           { fg = c.green })
hi("DiagnosticHint",         { fg = c.pink })
hi("DiagnosticUnderlineError", { undercurl = true, sp = c.red })
hi("DiagnosticUnderlineWarn",  { undercurl = true, sp = c.yellow })
hi("DiagnosticUnderlineInfo",  { undercurl = true, sp = c.blue })
hi("DiagnosticUnderlineOk",    { undercurl = true, sp = c.green })
hi("DiagnosticUnderlineHint",  { undercurl = true, sp = c.pink })
hi("DiagnosticVirtualTextError", { fg = c.red })
hi("DiagnosticVirtualTextWarn",  { fg = c.yellow })
hi("DiagnosticVirtualTextInfo",  { fg = c.blue })
hi("DiagnosticVirtualTextOk",    { fg = c.green })
hi("DiagnosticVirtualTextHint",  { fg = c.pink })

hi("LspReferenceText",  { bg = c.bg_variant })
hi("LspReferenceRead",  { bg = c.bg_variant })
hi("LspReferenceWrite", { bg = c.bg_variant })
hi("LspSignatureActiveParameter", { fg = c.yellow, bold = true })

-- Syntax ---------------------------------------------------------------------
hi("Comment",        { fg = c.fg_dim, italic = true })
hi("SpecialComment", { fg = c.fg_muted, italic = true })
hi("Constant",       { fg = c.blue })
hi("String",         { fg = c.green })
hi("Character",      { fg = c.green })
hi("Number",         { fg = c.yellow })
hi("Boolean",        { fg = c.yellow })
hi("Float",          { fg = c.yellow })
hi("Identifier",     { fg = c.fg })
hi("Function",       { fg = c.blue, bold = true })
hi("Statement",      { fg = c.pink })
hi("Conditional",    { fg = c.pink })
hi("Repeat",         { fg = c.pink })
hi("Label",          { fg = c.pink })
hi("Operator",       { fg = c.pink })
hi("Keyword",        { fg = c.pink, bold = true })
hi("Exception",      { fg = c.red })
hi("PreProc",        { fg = c.purple })
hi("Include",        { fg = c.purple })
hi("Define",         { fg = c.purple })
hi("Macro",          { fg = c.purple })
hi("Type",           { fg = c.yellow })
hi("StorageClass",   { fg = c.yellow })
hi("Structure",      { fg = c.yellow })
hi("Typedef",        { fg = c.yellow })
hi("Special",        { fg = c.aqua })
hi("SpecialChar",    { fg = c.pink })
hi("Tag",            { fg = c.blue })
hi("Delimiter",      { fg = c.fg_muted })
hi("Error",          { fg = c.red })
hi("Todo",           { fg = c.on_yellow, bg = c.yellow, bold = true })

-- Treesitter -----------------------------------------------------------------
links("@comment",         "Comment")
links("@comment.documentation", "Comment")
links("@string",          "String")
links("@character",       "Character")
links("@number",          "Number")
links("@boolean",         "Boolean")
links("@float",           "Float")
links("@constant",        "Constant")
links("@constant.builtin", "Constant")
links("@variable",        "Identifier")
links("@variable.builtin", "Identifier")
links("@variable.parameter", "Identifier")
links("@variable.member", "Identifier")
links("@function",        "Function")
links("@function.builtin", "Function")
links("@function.call",   "Function")
links("@method",          "Function")
links("@constructor",     "Type")
links("@keyword",         "Keyword")
links("@keyword.operator", "Operator")
links("@operator",        "Operator")
links("@conditional",     "Conditional")
links("@repeat",          "Repeat")
links("@label",           "Label")
links("@type",            "Type")
links("@type.builtin",    "Type")
links("@property",        "Identifier")
links("@field",           "Identifier")
links("@namespace",       "Type")
links("@punctuation.bracket", "Delimiter")
links("@punctuation.delimiter", "Delimiter")
links("@tag",             "Tag")
links("@tag.attribute",   "Identifier")
links("@text.underline",  "Underlined")
links("@markup.link",     "Underlined")
links("@markup.heading",  "Title")
links("@markup.raw",      "String")

-- Git / diff -----------------------------------------------------------------
hi("DiffAdd",      { bg = c.bg_dim, fg = c.green })
hi("DiffChange",   { bg = c.bg_dim, fg = c.yellow })
hi("DiffDelete",   { bg = c.bg_dim, fg = c.red })
hi("DiffText",     { bg = c.bg_variant, fg = c.yellow, bold = true })
hi("GitSignsAdd",    { fg = c.green })
hi("GitSignsChange", { fg = c.yellow })
hi("GitSignsDelete", { fg = c.red })
links("Added",   "DiffAdd")
links("Changed", "DiffChange")
links("Removed", "DiffDelete")

-- Common plugins -------------------------------------------------------------
hi("TelescopeSelection",   { fg = c.green, bg = c.bg_variant, bold = true })
hi("TelescopeMatching",    { fg = c.yellow })
hi("TelescopeBorder",      { fg = c.pink })
hi("TelescopePromptTitle", { fg = c.on_green, bg = c.green, bold = true })
hi("WhichKey",             { fg = c.pink })
hi("WhichKeyGroup",        { fg = c.blue })
hi("WhichKeyDesc",         { fg = c.fg })
hi("WhichKeySeparator",    { fg = c.fg_dim })
hi("LazyNormal",           { fg = c.fg, bg = c.bg_dim })
hi("LazyButton",           { fg = c.fg, bg = c.bg_variant })
hi("LazyButtonActive",     { fg = c.on_green, bg = c.green })
hi("NoicePopup",           { fg = c.fg, bg = c.bg_dim })
hi("BlinkCmpMenu",         { fg = c.fg, bg = c.bg_dim })
hi("BlinkCmpKind",         { fg = c.pink })
hi("IblIndent",            { fg = c.bg_variant, nocombine = true })
hi("IblScope",             { fg = c.fg_dim, nocombine = true })

-- Built-in terminal ANSI -----------------------------------------------------
local ansi = {
    "{{colors.terminal_normal_black.default.hex}}",
    "{{colors.terminal_normal_red.default.hex}}",
    "{{colors.terminal_normal_green.default.hex}}",
    "{{colors.terminal_normal_yellow.default.hex}}",
    "{{colors.terminal_normal_blue.default.hex}}",
    "{{colors.terminal_normal_magenta.default.hex}}",
    "{{colors.terminal_normal_cyan.default.hex}}",
    "{{colors.terminal_normal_white.default.hex}}",
}
for i, col in ipairs(ansi) do
    vim.g["terminal_color_" .. (i - 1)] = col
end
